"""Adiciona coluna logo na tabela fornecedor

Revision ID: 24a50542b3be
Revises: 8dd9a51ebad2
Create Date: 2025-03-02 23:00:40.709046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a50542b3be'
down_revision = '8dd9a51ebad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('custo_por_kwh', sa.Float(), nullable=False),
    sa.Column('limite_minimo_kwh', sa.Integer(), nullable=False),
    sa.Column('num_clientes', sa.Integer(), nullable=False),
    sa.Column('avaliacao_media', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
