"""Inicializando tabelas

Revision ID: 8dd9a51ebad2
Revises: 
Create Date: 2025-03-03 01:37:43.311948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd9a51ebad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('custo_por_kwh', sa.Float(), nullable=False),
    sa.Column('limite_minimo_kwh', sa.Integer(), nullable=False),
    sa.Column('num_clientes', sa.Integer(), nullable=False),
    sa.Column('avaliacao_media', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
